version: "3.9"
services:
  currency-exchange-service:
    build: .
    ports:
      - "8000:8000"
    networks:
      - currency-network

networks:
  currency-network:
    name: currency-network
    driver: bridge

